<a href="https://colab.research.google.com/github/evapatel123/semantic-search/blob/main/Copy_of_12_Semantic_Search_Answer_Key.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q sentence-transformers
from sentence_transformers import SentenceTransformer
import torch

**Steps**:

1. Open [this text file](https://drive.google.com/file/d/1GH3qgDSl7RzJqjx2tPFM783FkaQh_ei1/view?usp=sharing) and download it.
2. Upload the file to the Files section in the menu on the left sidebar of this notebook.
3. Write a `print()` statement to log the contents of this file to the console.

Your output should look like 8 sentences about the water cycle, each one printed on a new line.

In [ ]:
# Open the water_cycle.txt file in read mode with UTF-8 encoding
with open("water_cycle.txt", "r", encoding="utf-8") as file:
  # Read the entire contents of the file and store it in a variable
  water_cycle_text = file.read()

# Print the text below
print(water_cycle_text)

The water cycle describes how water moves through Earth's systems.
Water evaporates from oceans, lakes, and rivers.
It rises into the atmosphere and cools to form clouds.
This process is called condensation.
Eventually, the water falls back to Earth as precipitation, such as rain or snow.
Some of this water runs off into bodies of water, and some soaks into the ground.
This groundwater may be taken up by plants or may eventually return to lakes and oceans.
The cycle then repeats.


In [ ]:
def preprocess_text(text):
  # Strip extra whitespace from the beginning and the end of the text
  cleaned_text = text.strip()

  # Split the cleaned_text by every newline character (\n)
  chunks = cleaned_text.split("\n")

  # Create an empty list to store cleaned chunks
  cleaned_chunks = []

  # Write your for-in loop below to clean each chunk and add it to the cleaned_chunks list
  # This is only one way scholars may write this, but there are other ways!
  for chunk in chunks:
    stripped_chunk = chunk.strip()
    if len(stripped_chunk) > 0:
      cleaned_chunks.append(stripped_chunk)

  # Print cleaned_chunks
  print(cleaned_chunks)

  # Print the length of cleaned_chunks
  print(len(cleaned_chunks))

  # Return the cleaned_chunks
  return cleaned_chunks

# Call the preprocess_text function and store the result in a cleaned_chunks variable
cleaned_chunks = preprocess_text(water_cycle_text)

["The water cycle describes how water moves through Earth's systems.", 'Water evaporates from oceans, lakes, and rivers.', 'It rises into the atmosphere and cools to form clouds.', 'This process is called condensation.', 'Eventually, the water falls back to Earth as precipitation, such as rain or snow.', 'Some of this water runs off into bodies of water, and some soaks into the ground.', 'This groundwater may be taken up by plants or may eventually return to lakes and oceans.', 'The cycle then repeats.']
8


In [ ]:
# Load the pre-trained embedding model that converts text to vectors
model = SentenceTransformer('all-MiniLM-L6-v2')

def create_embeddings(text_chunks):
  # Convert each text chunk into a vector embedding and store as a tensor
  chunk_embeddings = model.encode(text_chunks, convert_to_tensor=True) # Replace ... with the cleaned_chunks list

  # Print the chunk embeddings
  print(chunk_embeddings)

  # Print the shape of chunk_embeddings
  print(chunk_embeddings.shape)

  # Return the chunk_embeddings
  return chunk_embeddings

# Call the create_embeddings function and store the result in a new chunk_embeddings variable
chunk_embeddings = create_embeddings(cleaned_chunks) # Complete this line

tensor([[-0.0245, -0.0096,  0.0576,  ...,  0.0437,  0.0573, -0.0108],
        [-0.0095,  0.0429,  0.0867,  ..., -0.0189,  0.0830, -0.0185],
        [ 0.0024,  0.0155,  0.0385,  ...,  0.0427,  0.0409,  0.0517],
        ...,
        [ 0.0218,  0.0212,  0.0578,  ...,  0.0293,  0.1006,  0.0448],
        [-0.0664,  0.0248,  0.0789,  ..., -0.0100,  0.1207, -0.0461],
        [ 0.0036, -0.0516, -0.0076,  ..., -0.0219,  0.0422, -0.0600]])
torch.Size([8, 384])


In [ ]:
# Define a function to find the most relevant text chunks for a given query, chunk_embeddings, and text_chunks
def get_top_chunks(query, chunk_embeddings, text_chunks):
  # Convert the query text into a vector embedding
  query_embedding = model.encode(query, convert_to_tensor=True) # Complete this line

  # Normalize the query embedding to unit length for accurate similarity comparison
  query_embedding_normalized = query_embedding / query_embedding.norm()

  # Normalize all chunk embeddings to unit length for consistent comparison
  chunk_embeddings_normalized = chunk_embeddings / chunk_embeddings.norm(dim=1, keepdim=True)

  # Calculate cosine similarity between all chunks and the query using matrix multiplication
  similarities = torch.matmul(chunk_embeddings_normalized, query_embedding_normalized) # Complete this line

  # Print the similarities
  print(similarities)

  # Find the indices of the 3 chunks with highest similarity scores
  top_indices = torch.topk(similarities, k=3).indices

  # Print the top indices
  print(top_indices)

  # Create an empty list to store the most relevant chunks
  top_chunks = []

  # Loop through the top indices and retrieve the corresponding text chunks
  # This is only one way scholars may write this, but there are other ways!
  for i in top_indices:
    chunk = text_chunks[i]
    top_chunks.append(chunk)

  # ===== SPICY CHALLENGE: LIST COMPREHENSION =====
  # top_chunks = [chunks[i] for i in top_indices]

  # Return the list of most relevant chunks
  return top_chunks

In [ ]:
# Call the get_top_chunks function with the original query
top_results = get_top_chunks("How does water get into the sky?", chunk_embeddings, cleaned_chunks) # Complete this line

# Print the top results
print(top_results)

tensor([0.5336, 0.5785, 0.6545, 0.3595, 0.5942, 0.5536, 0.4133, 0.1583])
tensor([2, 4, 1])
['It rises into the atmosphere and cools to form clouds.', 'Eventually, the water falls back to Earth as precipitation, such as rain or snow.', 'Water evaporates from oceans, lakes, and rivers.']


In [ ]:
# ===== LOAD & PROCESS YOUR NEW CONTENT =====
with open("space.txt", "r", encoding="utf-8") as file:
  space_text = file.read()

print(space_text)

# ===== APPLY THE COMPLETE WORKFLOW =====
space_cleaned_chunks = preprocess_text(space_text)
space_chunk_embeddings = create_embeddings(space_cleaned_chunks)

print("QUESTION 1: How long is a day on Jupiter?")
space_top_results = get_top_chunks("How long is a day on Jupiter?", space_chunk_embeddings, space_cleaned_chunks)
print(space_top_results)

# ===== EXPERIMENT & VERIFY =====
print("QUESTION 2: How many planets are in our solar system?")
space_top_results = get_top_chunks("How many planets are in our solar system?", space_chunk_embeddings, space_cleaned_chunks)
print(space_top_results)

print("QUESTION 3: What are exoplanets?")
space_top_results = get_top_chunks("What are exoplanets?", space_chunk_embeddings, space_cleaned_chunks)
print(space_top_results)

A planet is a large object that orbits a star.
To be a planet, an object must be massive enough for gravity to have squeezed it into a spherical, or round, shape.
It must also be large enough for gravity to have swept up any rocky or icy objects from its path, or orbit, around the star.
Scientists believe planets begin to form when a dense cloud of dust and gas, called a nebula, spins around a newly formed star.
Gradually, gravity causes the bits of matter in the nebula to clump together. 
Slowly, these clumps accumulate and grow. 
Eventually, these clumps become planets.
Earth is one of eight planets that circle the star we call the sun.
Together, the sun, the planets, and smaller objects such as moons make up our solar system.
The four planets closest to the sun—Mercury, Venus, Earth, and Mars—are called terrestrial planets. 
These planets are solid and rocky like Earth (terra means “earth” in Latin). 
Earth is the largest of the four terrestrial planets, and Mercury is the smallest.